import { Component, inject, OnInit, signal, ViewEncapsulation } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { BacklogDetails, ReferenceItem, SaveSprintRequest, SprintItem, SprintTaskItem, TaskApiService, WorkItemTypeReference } from '../../task-api.service';

@Component({ selector: 'app-backlog-page', standalone: true, imports: [], templateUrl: './backlog.html', styleUrl: './backlog.scss', encapsulation: ViewEncapsulation.None })
export class BacklogPage implements OnInit {
  private readonly api = inject(TaskApiService);
  readonly projects = signal<ReferenceItem[]>([]); readonly projectId = signal(''); readonly data = signal<BacklogDetails | null>(null); readonly loading = signal(false); readonly saving = signal(false); readonly error = signal(''); readonly message = signal('');
  readonly showEditor = signal(false); readonly editingId = signal<string | null>(null); readonly sprintProjectId = signal(''); readonly sprintName = signal(''); readonly sprintGoal = signal(''); readonly sprintStart = signal(''); readonly sprintEnd = signal(''); readonly draggedTask = signal<SprintTaskItem | null>(null); readonly dropTarget = signal('');
  readonly confirmationSprint = signal<SprintItem | null>(null); readonly confirmationAction = signal<'start' | 'complete' | null>(null);
  readonly showSaveConfirmation = signal(false);
  readonly workItemTypes = signal<WorkItemTypeReference[]>([]); readonly showBacklogItemEditor = signal(false); readonly showBacklogItemConfirmation = signal(false); readonly backlogItemProjectId = signal(''); readonly backlogItemTitle = signal(''); readonly backlogItemDescription = signal(''); readonly backlogItemType = signal('Bug'); readonly backlogItemPriority = signal('Medium'); readonly backlogItemDueDate = signal(''); readonly savingBacklogItem = signal(false); readonly backlogItemError = signal('');
  readonly createdBacklogProjectId = signal('');
  readonly sprintSelections = signal<Record<string, string>>({});
  ngOnInit() { this.api.getProjects().subscribe({ next: projects => this.projects.set(projects) }); this.api.getWorkItemTypeReferences().subscribe({ next: types => { this.workItemTypes.set(types); if (types.length) this.backlogItemType.set(types[0].key); } }); }
  selectProject(id: string) { this.projectId.set(id); this.data.set(null); if (id) this.load(); }
  load() { if (!this.projectId()) return; this.loading.set(true); this.error.set(''); this.api.getBacklog(this.projectId()).subscribe({ next: data => { this.data.set(data); this.loading.set(false); }, error: () => { this.loading.set(false); this.error.set('Backlog could not be loaded.'); } }); }
  assignableSprints() { return (this.data()?.sprints ?? []).filter(sprint => sprint.status === 'Active' || sprint.status === 'Planned'); }
  backlogRows() {
    const plan = this.data();
    if (!plan) return [];
    return [
      ...plan.backlog.map(task => ({ task, sprint: null as SprintItem | null })),
      ...plan.sprints.flatMap(sprint => sprint.tasks.map(task => ({ task, sprint }))),
    ];
  }
  selectSprint(taskId: string, sprintId: string) { this.sprintSelections.update(values => ({ ...values, [taskId]: sprintId })); }
  assignToSprint(task: SprintTaskItem) { const sprintId = this.sprintSelections()[task.id]; if (!sprintId) { this.error.set(`Select a sprint for ${task.taskNumber}.`); return; } const sprint = this.assignableSprints().find(item => item.id === sprintId); if (!sprint) { this.error.set('The selected sprint is no longer available.'); return; } this.saving.set(true); this.error.set(''); this.message.set(''); this.api.assignTaskToSprint(task.id, sprintId).subscribe({ next: () => { this.saving.set(false); this.message.set(`${task.taskNumber} assigned to ${sprint.name}.`); this.load(); }, error: (error: HttpErrorResponse) => { this.saving.set(false); this.error.set(error.error?.message || 'Task could not be assigned to the sprint.'); } }); }
  openCreate() { this.editingId.set(null); this.sprintProjectId.set(''); this.sprintName.set(`Sprint ${(this.data()?.sprints.length ?? 0) + 1}`); this.sprintGoal.set(''); this.sprintStart.set(''); this.sprintEnd.set(''); this.error.set(''); this.showEditor.set(true); }
  openEdit(sprint: SprintItem) { this.editingId.set(sprint.id); this.sprintProjectId.set(sprint.projectId); this.sprintName.set(sprint.name); this.sprintGoal.set(sprint.goal ?? ''); this.sprintStart.set(sprint.startDate ?? ''); this.sprintEnd.set(sprint.endDate ?? ''); this.error.set(''); this.showEditor.set(true); }
  closeEditor() { if (!this.saving()) this.showEditor.set(false); }
  openBacklogItemEditor() { this.backlogItemProjectId.set(''); this.backlogItemTitle.set(''); this.backlogItemDescription.set(''); this.backlogItemPriority.set('Medium'); this.backlogItemDueDate.set(''); this.backlogItemError.set(''); this.showBacklogItemEditor.set(true); }
  closeBacklogItemEditor() { if (!this.savingBacklogItem()) { this.showBacklogItemEditor.set(false); this.showBacklogItemConfirmation.set(false); } }
  requestSaveBacklogItem() { if (!this.backlogItemProjectId() || !this.backlogItemTitle().trim()) { this.backlogItemError.set('Project and title are required.'); return; } this.backlogItemError.set(''); this.showBacklogItemConfirmation.set(true); }
  closeBacklogItemConfirmation() { if (!this.savingBacklogItem()) this.showBacklogItemConfirmation.set(false); }
  saveBacklogItem() { if (!this.backlogItemProjectId() || !this.backlogItemTitle().trim()) return; this.showBacklogItemConfirmation.set(false); this.savingBacklogItem.set(true); this.api.createTask({ title: this.backlogItemTitle().trim(), description: this.backlogItemDescription().trim() || null, type: this.backlogItemType(), priority: this.backlogItemPriority(), severity: this.backlogItemPriority(), projectId: this.backlogItemProjectId(), epicId: null, softwareApplicationId: null, dueDate: this.backlogItemDueDate() || null, customFields: [] }).subscribe({ next: () => { this.savingBacklogItem.set(false); this.showBacklogItemEditor.set(false); const createdProjectId = this.backlogItemProjectId(); const projectName = this.projects().find(project => project.id === createdProjectId)?.name ?? 'the selected project'; this.createdBacklogProjectId.set(createdProjectId); this.message.set(`Backlog item created in ${projectName}.`); if (this.projectId() === createdProjectId) this.load(); }, error: (error: HttpErrorResponse) => { this.savingBacklogItem.set(false); this.backlogItemError.set(error.error?.message || 'Backlog item could not be created.'); } }); }
  viewCreatedBacklog() { const projectId = this.createdBacklogProjectId(); if (!projectId) return; this.projectId.set(projectId); this.data.set(null); this.load(); this.createdBacklogProjectId.set(''); }
  requestSaveSprint() { if (!this.sprintProjectId()) { this.error.set('Select a project for the sprint.'); return; } if (!this.sprintName().trim()) { this.error.set('Sprint name is required.'); return; } this.error.set(''); this.showSaveConfirmation.set(true); }
  closeSaveConfirmation() { if (!this.saving()) this.showSaveConfirmation.set(false); }
  requestSprintAction(sprint: SprintItem, action: 'start' | 'complete') { this.confirmationSprint.set(sprint); this.confirmationAction.set(action); }
  closeSprintConfirmation() { if (this.saving()) return; this.confirmationSprint.set(null); this.confirmationAction.set(null); }
  confirmSprintAction() { const sprint = this.confirmationSprint(); const action = this.confirmationAction(); if (!sprint || !action) return; this.confirmationSprint.set(null); this.confirmationAction.set(null); action === 'start' ? this.start(sprint) : this.complete(sprint); }
  saveSprint() { if (!this.sprintProjectId()) { this.error.set('Select a project for the sprint.'); return; } if (!this.sprintName().trim()) { this.error.set('Sprint name is required.'); return; } this.showSaveConfirmation.set(false); const request: SaveSprintRequest = { name: this.sprintName().trim(), goal: this.sprintGoal().trim() || null, projectId: this.sprintProjectId(), startDate: this.sprintStart() || null, endDate: this.sprintEnd() || null }; this.saving.set(true); this.error.set(''); const call = this.editingId() ? this.api.updateSprint(this.editingId()!, request) : this.api.createSprint(request); call.subscribe({ next: () => { this.saving.set(false); this.showEditor.set(false); this.message.set(this.editingId() ? 'Sprint updated.' : 'Sprint created.'); if (this.projectId()) this.load(); }, error: (error: HttpErrorResponse) => { this.saving.set(false); this.error.set(error.error?.message || 'Sprint could not be saved.'); } }); }
  start(sprint: SprintItem) { this.saving.set(true); this.error.set(''); this.api.startSprint(sprint.id).subscribe({ next: () => { this.saving.set(false); this.message.set(`${sprint.name} started.`); this.load(); }, error: (error: HttpErrorResponse) => { this.saving.set(false); this.error.set(error.error?.message || 'Sprint could not be started.'); } }); }
  complete(sprint: SprintItem) { this.saving.set(true); this.error.set(''); this.api.completeSprint(sprint.id).subscribe({ next: () => { this.saving.set(false); this.message.set(`${sprint.name} completed. Unfinished tasks returned to the backlog.`); this.load(); }, error: (error: HttpErrorResponse) => { this.saving.set(false); this.error.set(error.error?.message || 'Sprint could not be completed.'); } }); }
  startDrag(task: SprintTaskItem, event: DragEvent) { this.draggedTask.set(task); event.dataTransfer?.setData('text/plain', task.id); }
  allowDrop(target: string, event: DragEvent) { event.preventDefault(); this.dropTarget.set(target); }
  endDrag() { this.draggedTask.set(null); this.dropTarget.set(''); }
  drop(sprintId: string | null, event: DragEvent) { event.preventDefault(); const task = this.draggedTask(); this.endDrag(); if (!task) return; this.saving.set(true); this.api.assignTaskToSprint(task.id, sprintId).subscribe({ next: () => { this.saving.set(false); this.message.set(sprintId ? `${task.taskNumber} assigned to sprint.` : `${task.taskNumber} moved to backlog.`); this.load(); }, error: (error: HttpErrorResponse) => { this.saving.set(false); this.error.set(error.error?.message || 'Task could not be moved.'); } }); }
  orderedSprints() { return [...(this.data()?.sprints ?? [])].sort((a, b) => Date.parse(b.createdAt) - Date.parse(a.createdAt)); }
  activeSprintExists() { return this.data()?.sprints.some(x => x.status === 'Active') ?? false; }
}
